name: Stale
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Stale:
    runs-on: ubuntu-latest
    steps:
      - uses: sonia-corporation/stale@1.29.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-stale-comment: Stale issue message
          pull-request-stale-comment: Stale pull request message
          issue-stale-label: no-issue-activity
          pull-request-stale-label: no-pr-activity
